### ISSUE TITLE
Why does only on elevator moves when i added listerf to each of them?

### ISSUE THREAD

**Issue by yonesko** [magwo/elevatorsaga#138]
Why does only on elevator moves when I added callback to each of them?
```javascript
{
    init: function(elevators, floors) {
        for (var e = 0; e < elevators.length; e++) {
            var elevator = elevators[e];
            elevator.on("idle", function() {
                elevator.goToFloor(0);
            });
            elevator.on("floor_button_pressed", function(floorNum ) {
                elevator.goToFloor(floorNum );
            });
        }
    },




 
        update: function(dt, elevators, floors) {
            // We normally don't need to do anything here
        }
}
```

**Comment by adisib** [comment]
At a glance it is likely due to grabbing the elevator object from the closure. The context closes when init returns, so at that point elevator will refer to the last elevator object when the idle event callback checks the closure for the elevator object.

As a solution, I think you can just use "this" instead of "elevator" in your event handlers.

**Comment by yonesko** [comment]
Thanks it worked! I am new to JS, but I am already hating it ! :)
